# Generated by Django 6.1.1 on 2026-09-12 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnosisList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnosisReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=15)),
                ('year', models.SmallIntegerField()),
                ('blood_pressure', models.JSONField()),
                ('heart_rate', models.JSONField()),
                ('respiratory_rate', models.JSONField()),
                ('temperature', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientLabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_result', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField()),
                ('profile_picture', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=40)),
                ('emergency_contact', models.CharField(max_length=40)),
                ('insurance_type', models.CharField(max_length=100)),
                ('diagnosis_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.patientdiagnosislist')),
                ('diagnosis_readings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.patientdiagnosisreadings')),
                ('lab_results', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.patientlabresult')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
