# Generated by Django 6.1.1 on 2026-09-12 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientdiagnosislist_patientdiagnosisreadings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='diagnosis_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.patientdiagnosislist'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='diagnosis_readings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.patientdiagnosisreadings'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='lab_results',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.patientlabresult'),
        ),
    ]
