# Generated by Django 6.1.1 on 2026-09-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patientprofile_diagnosis_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='diagnosis_list',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='diagnosis_readings',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='lab_results',
        ),
        migrations.AddField(
            model_name='patientdiagnosislist',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patientprofile'),
        ),
        migrations.AddField(
            model_name='patientdiagnosisreadings',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patientprofile'),
        ),
        migrations.AddField(
            model_name='patientlabresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patientprofile'),
        ),
    ]
